//
//  LibraryInitializer.swift
//  MP
//
//  Created by aleksej on 3/23/24.
//

import Foundation
import Firebase

class LibraryInitializer {
     private static var books: [Book] = [
        Book(title: "Dog Man: The Scarlet Shedder: A Graphic Novel (Dog Man #12): From the Creator of Captain Underpants",
             authors: ["Dav Pilkey"],
             rating: 4.8,
             ratingsNumber: 281,
             description: "Our canine superhero returns in DOG MAN: THE SCARLET SHEDDER, the suspenseful and hilarious twelfth graphic novel in the #1 worldwide bestselling series by award-winning author and illustrator Dav Pilkey!",
             price: 9.99,
             imagesLinks: ["713-J3tw46L._AC_UL600_SR600,400_.jpg", "91kM7breuZL._SL1500_.jpg", "81gIATnRuPL._SL1500_.jpg", "913iHkBkP1L._SL1500_.jpg", "81GNaF6-BLL._SL1500_.jpg", "71UdHGwwFYL._SL1500_.jpg", "91nHVJptbnL._SL1500_.jpg"]),
        Book(title: "The Small and the Mighty: Twelve Unsung Americans Who Changed the Course of History, From the Founding to the Civil Rights Movement",
             authors: ["Sharon McMahon"],
             rating: 0,
             ratingsNumber: 0,
             description: "From America’s favorite government teacher, a heartfelt, inspiring portrait of twelve ordinary Americans whose courage formed the character of our country.",
             price: 32.00,
             imagesLinks: ["81xr8NFcd9L._AC_UL600_SR600,400_.jpg"]),
        Book(title: "The Women: A Novel",
             authors: ["Kristin Hannah"],
             rating: 4.8,
             ratingsNumber: 46494,
             description: "From the celebrated author of The Nightingale and The Four Winds comes Kristin Hannah's The Women―at once an intimate portrait of coming of age in a dangerous time and an epic tale of a nation divided.",
             price: 13.95,
             imagesLinks: ["913C+MR3S5L._AC_UL600_SR600,400_.jpg"]),
        Book(title: "How to Catch the Easter Bunny",
             authors: ["Adam Wallace", "Andy Elkerton"],
             rating: 4.8,
             ratingsNumber: 9131,
             description: "The New York Times and USA Today Bestseller! The best Easter basket stuffer and fun spring picture book for kids!",
             price: 2.75,
             imagesLinks: ["810bsxh1MmL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "It's Not Easy Being a Bunny: An Easter Book for Kids (Beginner Books(R))",
             authors: ["Marilyn Sadler", "Roger Bollen"],
             rating: 4.8,
             ratingsNumber: 19115,
             description: "P.J. Funnybunny doesn't want to be a bunny anymore! In this hilarious Beginner Book, a young bunny explores life with different animal friends. And don’t miss the charming follow-up, It’s Better Being a Bunny, available now! This is a perfect gift for Easter or celebrating bunnies all year round.",
             price: 29.25,
             imagesLinks: ["71ihGxMQEBL._AC_UL600_SR600,400_.jpg", "81MBNqDwuqL._SL1500_.jpg", "818riRiub0L._SL1500_.jpg", "81FnmWb-F1L._SL1500_.jpg", "81NoDZi+SjL._SL1500_.jpg", "81ZeZLjdy-L._SL1500_.jpg", "81SDNbDPYUL._SL1500_.jpg"]),
        Book(title: "Get It Together: Troubling Tales from the Liberal Fringe Hardcover",
             authors: ["Jesse Watters"],
             rating: 4.1,
             ratingsNumber: 31,
             description: "Can the political be way too personal? What if most radical activists are trying to change their lives by changing the whole country?",
             price: 18.49,
             imagesLinks: ["81uxN1LVsML._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Hippity, Hoppity, Little Bunny - Finger Puppet Board Book for Easter Basket Gifts or Stuffer Ages 0-3",
             authors: ["Cottage Door Press"],
             rating: 4.8,
             ratingsNumber: 5693,
             description: "Look no further than Hippity, Hoppity, Little Bunny for an adorable nursery rhyme book. Follow the little bunny rabbit and its adorable bird friends in this finger puppet book as they hunt for Easter eggs. Wiggle the puppet to make the bunny in the story come alive! Boys and girls will love this board book surprise this holiday!",
             price: 2.25,
             imagesLinks: ["81mIz5vLAfL._AC_UL600_SR600,400_.jpg", "71JIpXHSQXL._SL1500_.jpg", "81UqYuK7VQL._SL1500_.jpg", "71YhR7LSTHL._SL1500_.jpg", "71A-WCdp1KL._SL1500_.jpg", "814IbVoNZoL._SL1500_.jpg", "81-dg6fALqL._SL1500_.jpg"]),
        Book(title: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
             authors: ["James Clear"],
             rating: 4.8,
             ratingsNumber: 125501,
             description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
             price: 15.81,
             imagesLinks: ["81YkqyaFVEL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Pete the Cat and the Easter Basket Bandit: Includes Poster, Stickers, and Easter Cards!: An Easter And Springtime Book For Kids",
             authors: ["James Dean", "Kimberly Dean"],
             rating: 4.8,
             ratingsNumber: 762,
             description: "Pete and his friends hunt for his missing Easter basket in this storybook—complete with a fold-out poster, stickers, and cards perfect for Easter celebrations!",
             price: 2.94,
             imagesLinks: ["91yskyVPAmL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Little Blue Truck's Springtime: An Easter And Springtime Book For Kids",
             authors: ["Alice Schertle", "Jill McElmurry"],
             rating: 4.8,
             ratingsNumber: 15849,
             description: "Celebrate the beauty of springtime with the #1 New York Times best-selling Little Blue Truck!",
             price: 2.23,
             imagesLinks: ["81uv7QtqJ0L._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Where's Bluey?: A Search-and-Find Book",
             authors: ["Penguin Young Readers Licenses"],
             rating: 4.8,
             ratingsNumber: 6145,
             description: "Find Bluey and Bingo in this search-and-find activity book!",
             price: 3.50,
             imagesLinks: ["81EmtXw0mrL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "The 48 Laws of Power",
             authors: ["Robert Greene"],
             rating: 4.7,
             ratingsNumber: 74823,
             description: "Amoral, cunning, ruthless, and instructive, this multi-million-copy New York Times bestseller is the definitive manual for anyone interested in gaining, observing, or defending against ultimate control – from the author of The Laws of Human Nature.",
             price: 14.40,
             imagesLinks: ["611X8GI7hpL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "The Housemaid",
             authors: ["Freida McFadden"],
             rating: 4.5,
             ratingsNumber: 268733,
             description: "Don't miss the New York Times and USA Today bestseller and addictive psychological thriller with a jaw-dropping twist that’s burning up Instagram and TikTok--Freida McFadden’s The Housemaid is perfect for fans of Ruth Ware, Lisa Jewell, and Verity.",
             price: 4.95,
             imagesLinks: ["81AHTyq2wVL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "Taylor Swift: A Little Golden Book Biography",
             authors: ["Wendy Loggia", "Elisa Chavarri"],
             rating: 4.9,
             ratingsNumber: 6781,
             description: "Help your little one dream big with a Little Golden Book biography about Taylor Swift, the Grammy Award–winning and multiplatinum artist. Little Golden Book biographies are the perfect introduction to nonfiction for young readers—as well as fans of all ages!",
             price: 1.99,
             imagesLinks: ["81NsX5gOJkL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Bluey: Easter",
             authors: ["Bluey"],
             rating: 4.9,
             ratingsNumber: 411,
             description: "Celebrate Easter with Bluey and Bingo in this fun storybook! Based on the wildly successful animated series Bluey, as seen on Disney+",
             price: 2.95,
             imagesLinks: ["81QkbRlPEEL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "Iron Flame (The Empyrean, 2)",
             authors: ["Rebecca Yarros"],
             rating: 4.7,
             ratingsNumber: 137727,
             description: "“The first year is when some of us lose our lives. The second year is when the rest of us lose our humanity.” ―Xaden Riorson",
             price: 19.31,
             imagesLinks: ["91n7p-j5aqL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "Happy Easter, Mouse! (If You Give...)",
             authors: ["Laura Numeroff", "Felicia Bond"],
             rating: 4.8,
             ratingsNumber: 3429,
             description: "Join Mouse from If You Give a Mouse a Cookie as he goes on an Easter egg hunt! Who is hiding eggs in Mouse’s house? This adorable board book combines an engaging Easter theme with a story about colors!",
             price: 2.95,
             imagesLinks: ["71sOjwYbBgL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Somebunny Loves You: A Sweet and Silly Easter Board Book for Babies and Toddlers (Punderland)",
             authors: ["Rose Rossner", "Jessica Gibson"],
             rating: 4.9,
             ratingsNumber: 583,
             description: "A USA Today bestseller! Tell your egg-stra special little peep that they make you very hoppy with this punderful Easter book and basket stuffer for babies and toddlers!",
             price: 2.05,
             imagesLinks: ["81VP91WWhSL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Try Not to Laugh Challenge",
             authors: ["Sarah J. Maas"],
             rating: 4.8,
             ratingsNumber: 166910,
             description: "Easter Joke Book for Kids: Easter Basket Stuffer for Boys, Girls, Teens & Adults, Fun Easter Activity Book with Cute ... Easter Activities for the Whole Family! The seductive and stunning #1 New York Times bestselling sequel to Sarah J. Maas's spellbinding A Court of Thorns and Roses.",
             price: 8.39,
             imagesLinks: ["41XZlhQ+5NL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "The Story of Easter: A Christian Easter Book for Kids (Little Golden Book)",
             authors: ["Jean Miller", "Jerry Smath"],
             rating: 4.9,
             ratingsNumber: 3486,
             description: "This Little Golden Book retelling of the Easter story is the perfect gift for children to learn true meaning of the holiday!",
             price: 1.67,
             imagesLinks: ["91Qg05rIE6L._AC_UL300_SR300,200_.jpg"]),
        Book(title: "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
             authors: ["Bessel van der Kolk M.D."],
             rating: 4.8,
             ratingsNumber: 73439,
             description: "“Essential reading for anyone interested in understanding and treating traumatic stress and the scope of its impact on society.” —Alexander McFarlane, Director of the Centre for Traumatic Stress Studies",
             price: 9.49,
             imagesLinks: ["71bVExi4yXL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "Fallen Gods (Deluxe Limited Edition)",
             authors: ["Rachel Van Dyken"],
             rating: 0,
             ratingsNumber: 0,
             description: "Preorder now and receive the stunning DELUXE LIMITED EDITION while supplies last―featuring gorgeous sprayed edges with stenciled artwork, as well as exclusive endpapers and special design features. This breathtaking collectible is only available on a limited first print run, a must-have for any book lover while supplies last in the US and Canada only.",
             price: 29.69,
             imagesLinks: ["81S-MAN7BbL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "Supercommunicators: How to Unlock the Secret Language of Connection",
             authors: ["Charles Duhigg"],
             rating: 4.4,
             ratingsNumber: 184,
             description: "“A winning combination of stories, studies, and guidance that might well transform the worst communicators you know into some of the best.”—Adam Grant, author of Think Again and Hidden Potential",
             price: 19.17,
             imagesLinks: ["81G2riKjx4L._AC_UL600_SR600,400_.jpg"]),
        Book(title: "I'm Glad My Mom Died",
             authors: ["Jennette McCurdy"],
             rating: 4.7,
             ratingsNumber: 66272,
             description: "A heartbreaking and hilarious memoir by iCarly and Sam & Cat star Jennette McCurdy about her struggles as a former child actor—including eating disorders, addiction, and a complicated relationship with her overbearing mother—and how she retook control of her life.",
             price: 23.12,
             imagesLinks: ["71x3UZ18tmL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "Fourth Wing (The Empyrean, 1)",
             authors: ["Rebecca Yarros"],
             rating: 4.8,
             ratingsNumber: 181880,
             description: "\"Suspenseful, sexy, and with incredibly entertaining storytelling, the first in Yarros' Empyrean series will delight fans of romantic, adventure-filled fantasy.\" ―Booklist, starred review",
             price: 16.99,
             imagesLinks: ["917Bc9C1MlL._AC_UL300_SR300,200_.jpg"]),
        Book(title: "A Court of Thorns and Roses (A Court of Thorns and Roses, 1)",
             authors: ["Sarah J. Maas"],
             rating: 4.6,
             ratingsNumber: 187339,
             description: "The sexy, action-packed first book in the #1 New York Times bestselling Court of Thorns and Roses series from Sarah J. Maas.",
             price: 8.50,
             imagesLinks: ["812XbpMDovL._AC_UL600_SR600,400_.jpg", "81RoHngdOML._SL1500_.jpg", "a_court_of_mist_and_fury_by_aireenscolor_df06rlr-fullview.jpg", "1 Te9xD4SE9ItIt0ywN9PPvw@2x.jpg", "images.jpg", "QWdsHWEerCMF.jpg", "AdWgsdwe.jpg"]),
        Book(title: "Easter Eggstravaganza Mad Libs: World's Greatest Word Game",
             authors: ["Roger Price", "Leonard Stern"],
             rating: 4.7,
             ratingsNumber: 2629,
             description: "Mad Libs is the world’s greatest word game and a great gift or activity for anyone who likes to laugh! Write in the missing words on each page to create your own hilariously funny stories all about Easter. ",
             price: 0.99,
             imagesLinks: ["818PqOiT44L._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Don't Believe Everything You Think: Why Your Thinking Is The Beginning & End Of Suffering (Beyond Suffering)",
             authors: ["Joseph Nguyen"],
             rating: 4.6,
             ratingsNumber: 7782,
             description: "Learn how to overcome anxiety, self-doubt & self-sabotage without needing to rely on motivation or willpower.",
             price: 15.36,
             imagesLinks: ["51xKFo2B+RL._AC_UL600_SR600,400_.jpg"]),
        Book(title: "Construction Site: Spring Delight: An Easter Lift-the-Flap Book (Goodnight, Goodnight, Construc)",
             authors: ["Sherri Duskey Rinker", "AG Ford"],
             rating: 4.8,
             ratingsNumber: 862,
             description: "Celebrate the coming of spring with the construction crew from the bestselling Goodnight, Goodnight, Construction Site series!",
             price: 3.97,
             imagesLinks: ["81xj1NY02TL._AC_UL600_SR600,400_.jpg", "81oyGTcyB1L._SL1000_.jpg", "71-crXxO-zL._SL1000_.jpg", "81+JuA1n9XL._SL1000_.jpg", "A1m2nOxCpKL._SL1500_.jpg", "918Uxz+NlTL._SL1500_.jpg", "91qHhj7TalL._SL1500_.jpg"]),
        Book(title: "Outlive: The Science and Art of Longevity",
             authors: ["Peter Attia MD", "Bill Gifford"],
             rating: 4.6,
             ratingsNumber: 12427,
             description: "“One of the most important books you’ll ever read.”—Steven D. Levitt, New York Times bestselling author of Freakonomics",
             price: 20.00,
             imagesLinks: ["71X9FMy66NL._SL1500_.jpg"]),
        		
    ]
    
    public static func LibraryInit() {
        let tableDBReference = Database.database(url: "https://mpproject-750b8-default-rtdb.europe-west1.firebasedatabase.app").reference(withPath: "Library")
        let jsonEncoder = JSONEncoder()
        var id = 0
        
        for nonRegisteredBook in books {
            do {
                id += 1
                nonRegisteredBook.ID = "\(id)"
                
                tableDBReference.child(nonRegisteredBook.ID).setValue(try JSONSerialization.jsonObject(with: jsonEncoder.encode(nonRegisteredBook), options: []))
            } catch {
                print("Error in encoding")
            }
        }
    }
}
